### ISSUE TITLE
added code for cn.wsj.com

### ISSUE THREAD

**Issue by proophetzhang** [danielmichaelni/let-me-read-wsj#1]
added: 

		"https://cn.wsj.com/articles/*",
   
		"https://www.facebook.com/flx/warn/?u=https%3A%2F%2Fcn.wsj.com%2Farticles%2F*",
     
not work...

**Comment by danielmichaelni** [comment]
This workaround does not work for cn.wsj.com.

The reason why this works is because WSJ lets Facebook users read the articles when they are shared on Facebook. Since Facebook is blocked in china, it's not necessary for WSJ China to let users read the articles through Facebook.

**Comment by proophetzhang** [comment]
Hi,I tried to accessed via VPN. But it does not work either for cn.wsj.com.
